######## DELETE ROUTE TABLE

# aws --region us-east-1 ec2 delete-route-table --route-table-id rtb-f26b2889

- name: Find Route Table {{routetable_dict.key}} for further Delete processing
#  include: roles/vpc/tasks/routetable-find.yaml
  include_role:
    name: aws_vpc_route_table
    tasks_from: route-table-find.yaml

# by default, lookup is "tag"
- name: Delete Route Table {{myroutetable_name}} in {{myvpc_name}} when found
  ec2_vpc_route_table:
    validate_certs: "{{validate_certs}}"
    region: "{{myvpc.region}}"
    vpc_id: "{{myvpc_id}}"
    lookup: id
    route_table_id: "{{myroutetable_id}}"
    state: absent
  register: route_table_deleted
  when: myroutetable_id != 0

#- debug: var=route_table_deleted
#- debug: var=myroutetable_id
