= my-osx
:toc:
:sectnums:

OSX setup instruction and tools

== initial setup

status
----
ckim-mbp:~ ckim$ df -h /
Filesystem     Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s5  466Gi   10Gi  430Gi     3%  484165 4881968715    0%   /
ckim-mbp:~ ckim$
----

- activate touch id
- create ssh key pair
----
ssh-keygen -b 2048 -t rsa
----
- enable passwordless sudo
----
sudo -i
echo 'ckim ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ckim
exit
----

- recover resolver and others
----
ckim-mbp:~ ckim$ tar ztf OneDrive\ -\ Juniper\ Networks\,\ Inc/ssh.tgz
ckim-mbp:~ ckim$ sudo mkdir /etc/resolver/
ckim-mbp:~ ckim$ tar zxf OneDrive\ -\ Juniper\ Networks\,\ Inc/resolver.tgz
ckim-mbp:~ ckim$ sudo mv etc/resolver/ /etc
ckim-mbp:~ ckim$ sudo rm -rf etc/
ckim-mbp:~ ckim$
ckim-mbp:~ ckim$ tar zxf OneDrive\ -\ Juniper\ Networks\,\ Inc/venv.tgz
----

== install/setup Apps

* Outlook

* Dashlane (https://www.dashlane.com/)

* Chrome - keep in dock
** SwitchyOmega for proxy
** Dashlane
** Evenote Web Clipper
** Google Voice
** Grammarly
** Pocket
** Pair Android message with messages.google.com


* Firefox (for proxy)
* Evernote - keep in dock
* Homebrew - https://brew.sh/
** Xcode
** watch terraform golang tree
** --cask wireshark


* Visual Studio Code
** Cmd+Shift+P: Shell Command: Install 'code' commmand in PATH
** AsciiDoc, go, HashiCorp Terraform, Python
** GitHub Copilot Nightly + GitHub Copilot Labs

* GNU stow
```
brew install stow
```

Private: https://github.com/kimcharli/ckim-dotfiles
```
git clone https://github.com/kimcharli/ckim-dotfiles $HOME/dotfiles
cd $HOME/dotfiles
scripts/restore.sh
```



* iTerm2 - https://iterm2.com/downloads.html
----
mv Downloads/iTerm.app/ /Applications/
curl -L https://iterm2.com/shell_integration/install_shell_integration.sh | bash
----

* SecureCRT
** backup/restore /Users/ckim/Documents/securecrt
** Global Options/General/Configuration Paths: /Users/ckim/Documents/securecrt/config
** Default Session Options/Terminal/Log File/Log file name: /Users/ckim/Documents/securecrt/logs/%S-%Y%M%D-%h%m.log

* VMware Fusion (BigSur requires 12)
** SecureCRT
*** backup /Users/ckim/win10-vm and enable share
*** Global Options/General/Configuration Paths: Z:\win10-vm\securecrt
*** Default Session Options/Terminal/Log File/Log file name: Z:\win10-vm\logs\%S-%Y%M%D-%h%m.log

* Snagit - https://myaccount.techsmith.com/MyProducts/Software
* VitalSource Bookshelf
* Kindle
* Dropbox
* Google Drive
* Docker
** enable kubernetes

* python poetry
```bash
mkdir -p /Users/ckim/Library/Application\ Support/pypoetry/venv/
curl -sSL https://install.python-poetry.org | sed 's/symlinks=False/symlinks=True/' | python3 -
```


vscode extension: Python Poetry

```bash
poetry new --name projectname --src projectroot
```


* Start OneDrive
* Raindrop.io
* VLC
* Microsoft Remote Desktop
* Lens - https://k8slens.dev


* Cisco AnyConnect
** set profiles


* widgets
** Magnet from App Store

* KakaoTalk
* WhatsApp


=== In cases and Deprecated
* Insomnia
* Zoom
* Omnigraffle
* Skype
* Slack
* Crashplan
* RealVNC - Safari supports vnc natively.

=== Chrome Extensions
* Raindrop.io

=== Safari Extensions
* Dashlane for Safari
* Grammarly
* Pocket
* Evernote Web Clipper
* Raindrop.io

=== Code Extensions
* Remote Container
* Remote SSH
* Python
* Automator - Quick Action - (files or folders in Finder.app + Run Shell Script - pass input as arguments + save as 'Open VS Code')
```shell
for f in "$@"; do open -a 'Visual Studio Code' "$@" ; done
```
in ~/Library/Services/Open\ VS\ Code.workflow

=== Brew apps
----
brew install wireshark
brew install kubectl kubectx kubecm kubecfg helm
brew install awscli
brew install tree golang jq
brew install multipass
----

=== Mac App Store
* KakaoTalk

== Device Drivers

=== Printer/Scanner
* HP


== Products
link:SRV-vSRX[SRX vSRX]

== local httpd

=== terminate and start up
```bash
ckim-mbp:my-osx.wiki ckim$ cd docker-compose/all/
ckim-mbp:all ckim$ docker-compose down
Stopping all_nginx_1 ... done
Removing all_nginx_1 ... done
ckim-mbp:all ckim$ docker-compose up -d
Creating all_nginx_1 ... done
ckim-mbp:all ckim$
```

### setup markdown reader environment

Attemped https://hub.docker.com/r/gitlab/gitlab-ce/, but it took heavy CPU load.



#### interim
for <file>.md, create <file>.html from <md-template>.html by replacing <context/> with the content of <file>.md

#### TODO: create ssi or fastcgi



## link:vpn-in-centos[vpn in centos]

## link:ssh-tunnel[ssh tunnel]

## mac docker
https://docs.docker.com/docker-for-mac/

some commands
----
docker -H unix:///var/run/docker.sock ps

curl --unix-socket /var/run/docker.sock http:///localhost/version
----

tested for https://raw.githubusercontent.com/kimcharli/my-osx/master/terraform/nginx-test/main.tf

////
:sourcedir: __special
include::{sourcedir}/md-renderer.html[]
////

// uri include is not supported - without allow-uri-read
// include::https://raw.githubusercontent.com/kimcharli/my-osx/master/terraform/nginx-test/main.tf[]

