FROM ubuntu:20.04

# Use this mode when you need zero interaction while installing or upgrading 
# the system via apt. It accepts the default answer for all questions.
ENV DEBIAN_FRONTEND noninteractive

# Make bash the default shell
ENV SHELL /bin/bash

# Use bash instead of sh
SHELL ["/bin/bash", "-c"]

# Install basic dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        swig \
        bash-completion \
        zip \
        unzip \
        vim \
        sudo \
        curl \
        tar \
        less \
        wget \
        git \
        bzip2 \
        gnupg \
        locales \
        lsb-release \
        openssh-client \
        ca-certificates \
        apt-transport-https \
        python3 \
        python3-dev \
        python3-pip \
        python3-wheel \
        python3-setuptools \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
        libreadline-dev \
        llvm \
        libncurses5-dev \
        xz-utils \
        tk-dev \
        libxml2-dev \
        libxmlsec1-dev \
        libffi-dev \
        liblzma-dev \
        && apt-get clean && \
        rm -rf /var/lib/apt/lists/*

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8