- name: 1st Wait 300 seconds for port 22 to become open
  wait_for:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    timeout: 300
    port: 22
    sleep: 10
  delegate_to: localhost
  ignore_errors: yes
- name: 2nd Wait 300 seconds for port 22 to become open
  wait_for:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    timeout: 300
    port: 22
    sleep: 10
  delegate_to: localhost
  #u14
  #sudo apt update
  #sudo apt-get -y install python-pip python-dev      #Installs Pip
  #sudo apt-get -y install build-essential libssl-dev libffi-dev    #Dependencies
  #sudo pip install markupsafe httplib2            #Dependencies
  #
  #sudo apt-get -y install docker.io
- name: install
  raw: "sudo apt update ; sudo apt -y install python-pip linux-image-extra-virtual docker.io ; sudo pip install docker-py ; sudo usermod -a -G docker ubuntu"
#- name: install apt packages
#  apt:
#    update_cache: yes
#    name: "{{item}}"
#  become: true
#  with_items:
#    - python-pip
#    - linux-image-extra-virtual
- name: wait for the docker be installed
  wait_for:
    path: /var/log/syslog
    search_regex: Started Docker Application Container Engine
