# got intermittent /var/lib/dpg/lock error
# TODO: need to wait appropriately
- name: 1st Wait 300 seconds for port 22 to become open
  wait_for:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    timeout: 300
    port: 22
    sleep: 10
  delegate_to: localhost
  ignore_errors: yes
- name: 2nd Wait 300 seconds for port 22 to become open
  wait_for:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    timeout: 300
    port: 22
    sleep: 10
  delegate_to: localhost
- name: install apt packages
  apt:
    update_cache: yes
    name: python-pip
  become: true
- name: install pip modules
  pip:
    name: "{{item}}"
  with_items:
    - ansible==2.3
    - httplib2
    - requests
  become: true
- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f /home/ubuntu/.ssh/id_rsa -q -N ""
  args:
    creates: /home/ubuntu/.ssh/id_rsa
- name: fetch all public ssh keys
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_keys
- authorized_key:
    key: "{{ item.0 }}"
    user: ubuntu
    state: present
  delegate_to: "{{ item.1 }}"
  with_nested:
    - "{{ ssh_keys.stdout }}"
    - "{{groups.appformix_controller}}"
- authorized_key:
    key: "{{ item.0 }}"
    user: ubuntu
    state: present
  delegate_to: "{{ item.1 }}"
  with_nested:
    - "{{ ssh_keys.stdout }}"
    - "{{groups.compute}}"
- name: copy over artiacts
  get_url:
    url: "{{item}}"
    dest: /var/tmp
  with_items: "{{apfmx_images}}"
  when: true
- name: unarchive
  unarchive:
    src: /var/tmp/appformix-2.10.0.tar.gz
    dest: /home/ubuntu
    remote_src: yes
- name: download ansible.cfg
  get_url:
    url: https://s3.amazonaws.com/cloud-appformix/ansible.cfg
    dest: /home/ubuntu/appformix-2.10.0
- name: create group_vars folder
  file:
    path: /home/ubuntu/appformix-2.10.0/inventory/group_vars
    state: directory
- name: Create hosts file
  template:
    src: hosts.j2
    dest: /home/ubuntu/appformix-2.10.0/inventory/hosts
- name: Copy all.yaml
  copy:
    src: all.yaml
    dest: /home/ubuntu/appformix-2.10.0/inventory/group_vars
# http://169.254.169.254/latest/meta-data/iam/security-credentials/ec2-admin-full/
# export AWS_SECRET_KEY=
# export AWS_ACCESS_KEY=
# export AWS_DEFAULT_REGION=us-east-1
# curl http://169.254.169.254/latest/meta-data/iam/security-credentials/ec2-admin-full/ | python -c 'import sys, json ; obj=json.load(sys.stdin); print "export AWS_DEFAULT_REGION=us-east-1\nexport AWS_SECRET_KEY={SecretAccessKey}\nexport AWS_ACCESS_KEY={AccessKeyId}".format(**obj) '
- name: Get Auth Data
  uri:
    url: "http://169.254.169.254/latest/meta-data/iam/security-credentials/{{vpcs[myvpc_name].ec2.apfmx_installer.iam_role}}/"
  register: client_secret
- debug: var=client_secret

# $ cat /opt/appformix/etc/appformix_token.rst
